// Order-of-Battle summary for all 24 scenarios.
// Used by the SplashScreen to show what units each side brings.
// Data extracted from the official scenario book.

export interface OBEntry { label: string; count: number }

export interface ScenarioOB {
  axis: OBEntry[];
  axisSurrender: number;
  allied: OBEntry[];
  alliedSurrender: number;
}

// Each scenario lists leaders (named), then squads/teams, then weapons.
// Counts include reinforcements where applicable.
export const SCENARIO_OBS: Record<string, ScenarioOB> = {
  scenario_01: {
    axis: [
      { label: 'Lt. v. Karsties', count: 1 },
      { label: 'Cpl. Winkler', count: 1 },
      { label: 'Rifle', count: 4 },
      { label: 'Light MG', count: 1 },
    ],
    axisSurrender: 5,
    allied: [
      { label: 'Sgt. Kovalev', count: 1 },
      { label: 'Cpl. Krylov', count: 1 },
      { label: 'Rifle', count: 8 },
      { label: 'Medium MG', count: 2 },
      { label: 'Light MG', count: 1 },
    ],
    alliedSurrender: 7,
  },
  fat_lipki: {
    axis: [
      { label: 'Lt. v. Karsties', count: 1 },
      { label: 'Cpl. Winkler', count: 1 },
      { label: 'Rifle', count: 4 },
      { label: 'Light MG', count: 1 },
    ],
    axisSurrender: 5,
    allied: [
      { label: 'Sgt. Kovalev', count: 1 },
      { label: 'Cpl. Krylov', count: 1 },
      { label: 'Rifle', count: 8 },
      { label: 'Medium MG', count: 2 },
      { label: 'Light MG', count: 1 },
    ],
    alliedSurrender: 7,
  },
  scenario_02: {
    axis: [
      { label: 'Lt. Schrader', count: 1 },
      { label: 'Sgt. Esser', count: 1 },
      { label: 'Sgt. Biermann', count: 1 },
      { label: 'Cpl. Reiterhaus', count: 1 },
      { label: 'Volksgrenadier', count: 3 },
      { label: 'Conscript', count: 5 },
      { label: 'Heavy MG', count: 2 },
      { label: 'Light MG', count: 2 },
    ],
    axisSurrender: 8,
    allied: [
      { label: 'Lt. Blankenship', count: 1 },
      { label: 'Sgt. Smith', count: 1 },
      { label: 'Cpl. Hubbard', count: 1 },
      { label: 'Elite', count: 2 },
      { label: 'Line', count: 6 },
      { label: 'Weapon Team', count: 1 },
      { label: 'Medium MG', count: 1 },
      { label: 'Light Mortar', count: 1 },
      { label: 'Radio 105mm', count: 1 },
    ],
    alliedSurrender: 9,
  },
  scenario_03: {
    axis: [
      { label: 'Lt. Schrader', count: 1 },
      { label: 'Sgt. Ganz', count: 1 },
      { label: 'Rifle', count: 6 },
      { label: 'Weapon Team', count: 1 },
      { label: 'Heavy MG', count: 1 },
      { label: 'Light MG', count: 3 },
    ],
    axisSurrender: 7,
    allied: [
      { label: 'Cpt. Egorov', count: 1 },
      { label: 'Sgt. Maisky', count: 1 },
      { label: 'Cpl. Gordov', count: 1 },
      { label: 'Militia', count: 10 },
      { label: 'Green', count: 1 },
      { label: 'Medium MG', count: 1 },
      { label: 'Light MG', count: 1 },
      { label: 'Wire', count: 12 },
    ],
    alliedSurrender: 10,
  },
  scenario_04: {
    axis: [
      { label: 'Lt. Lauerbach', count: 1 },
      { label: 'Lt. Schrader', count: 1 },
      { label: 'Elite Rifle', count: 6 },
      { label: 'Weapon Team', count: 3 },
      { label: 'IG 18 Gun', count: 1 },
      { label: 'Heavy MG', count: 2 },
      { label: 'Light MG', count: 2 },
      { label: 'Wire', count: 5 },
    ],
    axisSurrender: 8,
    allied: [
      { label: 'Lt. Wray', count: 1 },
      { label: 'Sgt. Buehler', count: 1 },
      { label: 'Sgt. White', count: 1 },
      { label: 'Elite', count: 6 },
      { label: 'Line', count: 6 },
      { label: 'Engineer', count: 2 },
      { label: '.50cal MG', count: 2 },
      { label: 'Medium MG', count: 2 },
      { label: 'Satchel Charge', count: 2 },
      { label: 'Radio 75mm', count: 1 },
      { label: 'Flamethrower', count: 2 },
    ],
    alliedSurrender: 11,
  },
  scenario_05: {
    axis: [
      { label: 'Lt. v. Karsties', count: 1 },
      { label: 'Sgt. Ganz', count: 1 },
      { label: 'Rifle', count: 3 },
      { label: 'Weapon Team', count: 1 },
      { label: 'Heavy MG', count: 1 },
      { label: 'Light MG', count: 2 },
      { label: 'Satchel Charge', count: 1 },
      { label: 'Trench', count: 6 },
    ],
    axisSurrender: 5,
    allied: [
      { label: 'Sgt. Bikovets', count: 1 },
      { label: 'Sgt. Kovalev', count: 1 },
      { label: 'Sgt. Kaminsky', count: 1 },
      { label: 'Sgt. Maisky', count: 1 },
      { label: 'Guards SMG', count: 12 },
    ],
    alliedSurrender: 12,
  },
  scenario_06: {
    axis: [
      { label: 'Sgt. Esser', count: 1 },
      { label: 'Sgt. Biermann', count: 1 },
      { label: 'Parachute', count: 3 },
      { label: 'Rifle', count: 3 },
      { label: 'Conscript', count: 3 },
      { label: 'Weapon Team', count: 2 },
      { label: 'Heavy MG', count: 2 },
      { label: 'Light MG', count: 3 },
    ],
    axisSurrender: 9,
    allied: [
      { label: 'Lt. Wray', count: 1 },
      { label: 'Sgt. Smith', count: 1 },
      { label: 'Cpl. Hubbard', count: 1 },
      { label: 'Paratroop', count: 10 },
      { label: 'Weapon Team', count: 2 },
      { label: 'Medium MG', count: 2 },
    ],
    alliedSurrender: 11,
  },
  scenario_07: {
    axis: [
      { label: 'Lt. Schrader', count: 1 },
      { label: 'Sgt. Biermann', count: 1 },
      { label: 'Volksgrenadier', count: 6 },
      { label: 'Light MG', count: 3 },
    ],
    axisSurrender: 8,
    allied: [
      { label: 'Sgt. Maisky', count: 1 },
      { label: 'Cpl. Bulganin', count: 1 },
      { label: 'SMG', count: 4 },
      { label: 'Militia', count: 4 },
      { label: 'Green', count: 4 },
      { label: 'Light MG', count: 4 },
      { label: 'Satchel Charge', count: 4 },
      { label: 'Light Mortar', count: 1 },
    ],
    alliedSurrender: 14,
  },
  scenario_08: {
    axis: [
      { label: 'Lt. Schrader', count: 1 },
      { label: 'Sgt. Ganz', count: 1 },
      { label: 'Rifle', count: 3 },
      { label: 'Light MG', count: 3 },
      { label: 'Foxholes', count: 3 },
    ],
    axisSurrender: 4,
    allied: [
      { label: 'Sgt. Kaminsky', count: 1 },
      { label: 'Sgt. Maisky', count: 1 },
      { label: 'Rifle', count: 10 },
      { label: 'Medium MG', count: 2 },
      { label: 'Light MG', count: 1 },
    ],
    alliedSurrender: 9,
  },
  scenario_09: {
    axis: [
      { label: 'Cpt. Wehling', count: 1 },
      { label: 'Sgt. Pfeiffer', count: 1 },
      { label: 'Sgt. Esser', count: 1 },
      { label: 'Sgt. Biermann', count: 1 },
      { label: 'Volksgrenadier', count: 8 },
      { label: 'Rifle', count: 1 },
      { label: 'Weapon Team', count: 3 },
      { label: 'Heavy MG', count: 1 },
      { label: 'Light MG', count: 5 },
      { label: 'Radio 81mm', count: 1 },
      { label: 'Mines', count: 3 },
    ],
    axisSurrender: 11,
    allied: [
      { label: 'Lt. Wray', count: 1 },
      { label: 'Lt. Esparza', count: 1 },
      { label: 'Lt. Blankenship', count: 1 },
      { label: 'Lt. Thomas', count: 1 },
      { label: 'Cpl. Hubbard', count: 1 },
      { label: 'Sgt. Smith', count: 1 },
      { label: 'Paratroop', count: 12 },
      { label: 'Medium MG', count: 1 },
      { label: 'Radio 105mm', count: 1 },
      { label: 'Satchel Charge', count: 3 },
    ],
    alliedSurrender: 13,
  },
  scenario_10: {
    axis: [
      { label: 'Lt. Schrader', count: 1 },
      { label: 'Sgt. Esser', count: 1 },
      { label: 'Sgt. Biermann', count: 1 },
      { label: 'Pionier', count: 2 },
      { label: 'Rifle', count: 4 },
      { label: 'Heavy MG', count: 1 },
      { label: 'Light MG', count: 2 },
      { label: 'Flamethrower', count: 1 },
      { label: 'Satchel Charge', count: 1 },
    ],
    axisSurrender: 7,
    allied: [
      { label: 'Lt. Khukovsky', count: 1 },
      { label: 'Sgt. Bikovets', count: 1 },
      { label: 'Guards SMG', count: 2 },
      { label: 'Guards Rifle', count: 2 },
      { label: 'Elite', count: 2 },
      { label: '.50cal MG', count: 1 },
      { label: 'Light MG', count: 2 },
      { label: 'Satchel Charge', count: 1 },
    ],
    alliedSurrender: 6,
  },
  scenario_11: {
    axis: [
      { label: 'Lt. Lauerbach', count: 1 },
      { label: 'Sgt. Ganz', count: 1 },
      { label: 'SS', count: 4 },
      { label: 'Weapon Team', count: 1 },
      { label: 'Heavy MG', count: 1 },
      { label: 'Light MG', count: 2 },
      { label: 'Wire', count: 14 },
      { label: 'Mines', count: 4 },
    ],
    axisSurrender: 6,
    allied: [
      { label: 'Sgt. White', count: 1 },
      { label: 'Sgt. Buehler', count: 1 },
      { label: 'Elite', count: 1 },
      { label: 'Line', count: 6 },
      { label: 'Weapon Team', count: 1 },
      { label: 'Satchel Charge', count: 2 },
      { label: 'Foxholes', count: 2 },
      { label: '.50cal MG', count: 1 },
      { label: 'Pack Howitzer', count: 1 },
      { label: 'Bunker', count: 1 },
    ],
    alliedSurrender: 7,
  },
  scenario_12: {
    axis: [
      { label: 'Sgt. Esser', count: 1 },
      { label: 'Sgt. Biermann', count: 1 },
      { label: 'Sgt. Pfeiffer', count: 1 },
      { label: 'Volksgrenadier', count: 9 },
      { label: 'Weapon Team', count: 2 },
      { label: 'Heavy MG', count: 1 },
      { label: 'Light MG', count: 2 },
      { label: 'Light Mortar', count: 1 },
      { label: 'Bunker', count: 1 },
      { label: 'Trench', count: 2 },
    ],
    axisSurrender: 10,
    allied: [
      { label: 'Lt. Oliveira', count: 1 },
      { label: 'Cpl. Pereira', count: 1 },
      { label: 'Cpl. Santos', count: 1 },
      { label: 'Sgt. Alves', count: 1 },
      { label: 'Line', count: 8 },
      { label: 'Green', count: 8 },
      { label: 'Weapon Team', count: 5 },
      { label: 'Medium MG', count: 2 },
      { label: 'Medium Mortar', count: 2 },
      { label: 'Light Mortar', count: 1 },
    ],
    alliedSurrender: 17,
  },
  scenario_13: {
    axis: [
      { label: 'Lt. v. Karsties', count: 1 },
      { label: 'Lt. Lauerbach', count: 1 },
      { label: 'Parachute', count: 6 },
    ],
    axisSurrender: 6,
    allied: [
      { label: 'Lt. Walker', count: 1 },
      { label: 'Sgt. Clarke', count: 1 },
      { label: 'Sgt. Scott', count: 1 },
      { label: 'Guards', count: 9 },
      { label: 'Light MG', count: 2 },
      { label: 'Light Mortar', count: 2 },
    ],
    alliedSurrender: 9,
  },
  scenario_14: {
    axis: [
      { label: 'Sgt. Biermann', count: 1 },
      { label: 'Lt. Lauerbach', count: 1 },
      { label: 'Rifle', count: 7 },
      { label: 'Weapon Team', count: 1 },
      { label: 'Light MG', count: 3 },
      { label: 'Light Mortar', count: 1 },
      { label: 'Foxholes', count: 1 },
    ],
    axisSurrender: 7,
    allied: [
      { label: 'Lt. Szymański', count: 1 },
      { label: 'Sgt. Wojcik', count: 1 },
      { label: 'Sgt. Nowak', count: 1 },
      { label: 'Line', count: 2 },
      { label: 'Regulars', count: 9 },
      { label: 'Light MG', count: 2 },
      { label: '81mm Mortar', count: 1 },
    ],
    alliedSurrender: 10,
  },
  scenario_15: {
    axis: [
      { label: 'Lt. Cornamă', count: 1 },
      { label: 'Sgt. Rozin', count: 1 },
      { label: 'Sgt. Stoica', count: 1 },
      { label: 'Cpl. Popescu', count: 1 },
      { label: 'Rifle', count: 6 },
      { label: 'Line', count: 14 },
      { label: 'Medium MG', count: 2 },
      { label: 'Light MG', count: 3 },
      { label: 'Brandt Mortar', count: 1 },
    ],
    axisSurrender: 17,
    allied: [
      { label: 'Lt. Gulkevich', count: 1 },
      { label: 'Cpl. Krylov', count: 1 },
      { label: 'Guards Rifle', count: 3 },
      { label: 'Rifle', count: 6 },
      { label: 'Militia', count: 3 },
      { label: 'Medium MG', count: 2 },
      { label: 'Light MG', count: 2 },
    ],
    alliedSurrender: 10,
  },
  scenario_16: {
    axis: [
      { label: 'Lt. v. Karsties', count: 1 },
      { label: 'Sgt. Ganz', count: 1 },
      { label: 'Cpl. Winkler', count: 1 },
      { label: 'Elite Rifle', count: 3 },
      { label: 'Rifle', count: 6 },
      { label: 'Weapon Team', count: 2 },
      { label: 'Heavy MG', count: 1 },
      { label: 'Light MG', count: 2 },
      { label: 'Light Mortar', count: 1 },
    ],
    axisSurrender: 10,
    allied: [
      { label: 'Cpl. Gough', count: 1 },
      { label: 'Cpl. Besson', count: 1 },
      { label: 'BAR', count: 4 },
      { label: 'Weapon Team', count: 2 },
      { label: 'Heavy MG', count: 1 },
      { label: 'Light MG', count: 1 },
      { label: '60mm Mortar', count: 1 },
      { label: 'Light Mortar', count: 1 },
      { label: 'Foxholes', count: 2 },
    ],
    alliedSurrender: 8,
  },
  scenario_17: {
    axis: [
      { label: 'Lt. Bolter', count: 1 },
      { label: 'Lt. Schrader', count: 1 },
      { label: 'Sgt. Ganz', count: 1 },
      { label: 'Parachute', count: 9 },
      { label: 'Weapon Team', count: 1 },
      { label: 'Heavy MG', count: 1 },
      { label: 'Light MG', count: 3 },
    ],
    axisSurrender: 9,
    allied: [
      { label: 'Lt. Petitclerc', count: 1 },
      { label: 'Sgt. Poutré', count: 1 },
      { label: "Smith, King's Hero", count: 1 },
      { label: 'Guards', count: 6 },
      { label: 'Line', count: 3 },
      { label: 'Elite', count: 3 },
      { label: 'Weapon Team', count: 1 },
      { label: 'Heavy MG', count: 1 },
      { label: 'Light MG', count: 3 },
      { label: 'Satchel Charge', count: 4 },
    ],
    alliedSurrender: 12,
  },
  scenario_18: {
    axis: [
      { label: 'Lt. Lauerbach', count: 1 },
      { label: 'Sgt. Biermann', count: 1 },
      { label: 'Rifle', count: 8 },
      { label: 'Light MG', count: 6 },
      { label: 'Radio 75mm', count: 1 },
    ],
    axisSurrender: 7,
    allied: [
      { label: 'Lt. Đorđević', count: 1 },
      { label: 'Sgt. Jovanović', count: 1 },
      { label: 'Rifle', count: 11 },
      { label: 'Green', count: 2 },
      { label: 'Heavy MG', count: 1 },
      { label: 'Light MG', count: 1 },
    ],
    alliedSurrender: 10,
  },
  scenario_19: {
    axis: [
      { label: 'Cpt. Wehling', count: 1 },
      { label: 'Lt. Huntziger', count: 1 },
      { label: 'Pionier', count: 3 },
      { label: 'Elite Rifle', count: 4 },
      { label: 'Weapon Team', count: 1 },
      { label: 'Light MG', count: 3 },
      { label: 'IG 18 Gun', count: 1 },
      { label: 'Flamethrower', count: 1 },
      { label: 'Satchel Charge', count: 2 },
    ],
    axisSurrender: 7,
    allied: [
      { label: 'Lt. Aivaliotis', count: 1 },
      { label: 'Sgt. Samaras', count: 1 },
      { label: 'Sgt. Giannidis', count: 1 },
      { label: 'Garrison', count: 9 },
      { label: 'Weapon Team', count: 1 },
      { label: 'Heavy MG', count: 2 },
      { label: 'Light MG', count: 1 },
      { label: "French '75", count: 1 },
      { label: 'Radio 75mm', count: 1 },
      { label: 'Bunker Complex', count: 1 },
    ],
    alliedSurrender: 8,
  },
  scenario_20: {
    axis: [
      { label: 'Cpt. Pajari', count: 1 },
      { label: 'Lt. Järvinen', count: 1 },
      { label: 'Sgt. Virtanen', count: 1 },
      { label: 'Sissi', count: 15 },
      { label: 'Light MG', count: 3 },
      { label: 'Molotov Cocktail', count: 8 },
    ],
    axisSurrender: 13,
    allied: [
      { label: 'Sgt. Kovalev', count: 1 },
      { label: 'Cpl. Krylov', count: 1 },
      { label: 'Cpl. Gordov', count: 1 },
      { label: 'Rifle', count: 15 },
      { label: 'Medium MG', count: 2 },
      { label: 'Light MG', count: 2 },
    ],
    alliedSurrender: 13,
  },
  scenario_21: {
    axis: [
      { label: 'Sgt. Ottolini', count: 1 },
      { label: 'Cpl. Brachetta', count: 1 },
      { label: 'Fucilieri', count: 12 },
      { label: 'Medium MG', count: 1 },
      { label: 'Light MG', count: 2 },
      { label: 'Brixia Mortar', count: 1 },
      { label: 'Foxholes', count: 5 },
      { label: 'Mines', count: 3 },
    ],
    axisSurrender: 10,
    allied: [
      { label: 'Sgt. Buehler', count: 1 },
      { label: 'Sgt. White', count: 1 },
      { label: 'Line', count: 8 },
      { label: 'Heavy MG', count: 1 },
      { label: 'Medium MG', count: 2 },
      { label: 'Light Mortar', count: 1 },
    ],
    alliedSurrender: 7,
  },
  scenario_22: {
    axis: [
      { label: 'Lt. Lauerbach', count: 1 },
      { label: 'Sgt. Biermann', count: 1 },
      { label: 'Volksgrenadier', count: 2 },
      { label: 'Conscript', count: 7 },
      { label: 'Heavy MG', count: 1 },
      { label: 'Light MG', count: 2 },
      { label: 'Medium Mortar', count: 1 },
      { label: 'Trench', count: 6 },
      { label: 'Wire', count: 6 },
    ],
    axisSurrender: 6,
    allied: [
      { label: 'Lt. Forbes', count: 1 },
      { label: 'Lt. Chatham', count: 1 },
      { label: 'Sgt. Casey', count: 1 },
      { label: 'Line', count: 9 },
      { label: 'Weapon Team', count: 2 },
      { label: 'Heavy MG', count: 1 },
      { label: 'Light MG', count: 3 },
      { label: 'Light Mortar', count: 1 },
    ],
    alliedSurrender: 12,
  },
  scenario_23: {
    axis: [
      { label: 'Lt. Pani', count: 1 },
      { label: 'Sgt. Rovena', count: 1 },
      { label: 'Fucilieri', count: 6 },
      { label: 'Weapon Team', count: 1 },
      { label: 'Light MG', count: 2 },
      { label: 'Medium Mortar', count: 1 },
      { label: 'Trench', count: 10 },
      { label: 'Mines', count: 5 },
    ],
    axisSurrender: 7,
    allied: [
      { label: 'Lt. Chatham', count: 1 },
      { label: 'Cpl. Singh', count: 1 },
      { label: 'Line', count: 3 },
      { label: 'Light MG', count: 2 },
      { label: 'Light Mortar', count: 1 },
      { label: 'Radio 88mm', count: 1 },
      { label: 'Trench', count: 10 },
      { label: 'Heavy MG', count: 1 },
      { label: 'Foxholes', count: 1 },
    ],
    alliedSurrender: 4,
  },
  scenario_24: {
    axis: [
      { label: 'Lt. Visconti', count: 1 },
      { label: 'Cpl. Radović', count: 1 },
      { label: 'Sgt. Marcello', count: 1 },
      { label: 'Fucilieri', count: 9 },
      { label: 'Guastatori', count: 2 },
      { label: 'Weapon Team', count: 2 },
      { label: 'Heavy MG', count: 1 },
      { label: 'Light MG', count: 2 },
      { label: 'Brixia Mortar', count: 1 },
      { label: 'Radio 105mm', count: 1 },
      { label: 'Satchel Charge', count: 2 },
    ],
    axisSurrender: 12,
    allied: [
      { label: 'Lt. Lyndhurst', count: 1 },
      { label: 'Cpl. Singh', count: 1 },
      { label: 'Territorial', count: 6 },
      { label: 'Weapon Team', count: 1 },
      { label: 'Heavy MG', count: 1 },
      { label: 'Light MG', count: 1 },
      { label: 'Light Mortar', count: 1 },
      { label: 'Foxholes', count: 6 },
    ],
    alliedSurrender: 7,
  },
};

export function getScenarioOB(id: string): ScenarioOB | null {
  return SCENARIO_OBS[id] ?? null;
}
